### ISSUE TITLE
Find a way to prevent - or detect - duplicate file names in a vault

### ISSUE THREAD

**Issue by claremacrae** [claremacrae/obsidian-experiments-plugin#1]
The wiki-style links depend on file-names being unique.

- Perhaps when creating new files, add a check and prevent duplicates.
- Or add a way to show duplicate file names (similar to Dangling Links plugin)

**Comment by claremacrae** [comment]
I ended up doing this with dataviewjs.

Here's what the code looked like. The `.toLowerCase()` is needed to treat file names as identical even if they differ by capitalisation only:

````text
```dataviewjs
function listFileNameIssues(dv) {  
    let pages = dv.pages();  
    let groups = pages.groupBy(p => p.file.name.toLowerCase())  
    for (let group of groups) {  
        let count = 0  
        for (let page of group.rows.sort(p => p.file.path, 'asc')) {  
            // dv.paragraph(page.file.path)  
            count += 1  
        }  
  
        if (count === 1 ) {  
            continue  
        }  
  
        for (let page of group.rows.sort(p => p.file.path, 'asc')) {  
            dv.paragraph(page.file.link + ': ' + page.file.path)  
        }  
    }  
}

listFileNameIssues(dv);
```
````

For a nice style, I put it in a red callout:


````text
> [!ERROR] Duplicate file names
> ```dataviewjs
> function listFileNameIssues(dv) {  
>     let pages = dv.pages();  
>     let groups = pages.groupBy(p => p.file.name.toLowerCase())  
>     for (let group of groups) {  
>         let count = 0  
>         for (let page of group.rows.sort(p => p.file.path, 'asc')) {  
>             // dv.paragraph(page.file.path)  
>             count += 1  
>         }  
>   
>         if (count === 1 ) {  
>             continue  
>         }  
>   
>         for (let page of group.rows.sort(p => p.file.path, 'asc')) {  
>             dv.paragraph(page.file.link + ': ' + page.file.path)  
>         }  
>     }  
> }
> 
> listFileNameIssues(dv);
> ```
````

In fact, I used [CustomJS](https://github.com/samlewis0602/obsidian-custom-js) to put the function somewhere central for re-use, so my actual code is:

````text
> > [!ERROR] Duplicate file names
> ```dataviewjs
> const {IssuesToCheck} = customJS
> IssuesToCheck.listFileNameIssues(dv)
> ```
````

**Comment by Chykg0** [comment]
Hello,

Just a big thank's for this script.
I'm a newbie in js and i had an issue with duplicated notes (i'm still wondering why...).
It's gonna help me a lot so thank you so much !

**Comment by claremacrae** [comment]
Hi @Chykg0 Oh wow, I had forgotten I even did this. I'm so pleased it was useful!

**Comment by MarioCurie** [comment]
@claremacrae I'm at the beginning of my path with Obsidian and I don't know much JS so I have a request.
Could you show the exact code you have in the note (md) and in the js file, including the file name f js file.
I installed CustomJS I tried different variants and it doesn't work for me.

**Comment by Ali-C-Ila** [comment]
This was functioning well for me, but recently it stopped working. Wondering if an Obsidian update broke it somehow?

(It returns nothing despite having duplicated file names in my vault.)

(dataview js is turned on, obsidian & dataview up-to-date)
![image](https://github.com/claremacrae/obsidian-experiments-plugin/assets/56729449/3fa0305b-7a81-4f4e-8364-e01bbf41e579)

**Comment by AnitaYCheng** [comment]
> This was functioning well for me, but recently it stopped working. Wondering if an Obsidian update broke it somehow?
> 
> (It returns nothing despite having duplicated file names in my vault.)
> 
> (dataview js is turned on, obsidian & dataview up-to-date) ![image](https://private-user-images.githubusercontent.com/56729449/345795958-3fa0305b-7a81-4f4e-8364-e01bbf41e579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2OTk2NDYsIm5iZiI6MTcyNjY5OTM0NiwicGF0aCI6Ii81NjcyOTQ0OS8zNDU3OTU5NTgtM2ZhMDMwNWItN2E4MS00ZjRlLTgzNjQtZTAxYmJmNDFlNTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDIyNDIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNTc5YTk5MTMzYjc5YjBiZjIxNzViMGNmMjJiODVkY2M2ZmI1MjM1ODlhODA3MGI5MTZjNTkwZjdjYTRkNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rV3RjlrYVerdoW8vJttF1uBhfS0A4cOdvkGtr-CxZnc)

Mine has `Enable inline JavaScript queries` turned on, and the script still works as of 5 minutes ago! (Thanks so much @claremacrae for this tool!)

**Comment by xsilvertom** [comment]
Thank you @claremacrae for skeleton and idea.
It still works and finds various files bearing same name but residing in various corners of The Vault.
However I came here from sync issues pages where problem is that tools like MS OneDrive does sync files whenever they like, not when file is changed. And that makes some files unsynced when opened on secondary PC (both Win 10 Pro). And such file is made a "duplicate" with PC hostname as a suffix.
So ending with:
original.md
original-hostname.md

Might have something to do with sync and also Obsidian workspace saved as those files are remembered to get open on Obsidian start, but as those might be unsynced, then clone is made.

Unfortunately on one PC a OneDrive shows all synced, but on other always shows 413 files syncing, but that never gets done, regardless MS shows those are just few MB. And no, there is no way that MS shows WHICH files are not syncing (their services are getting worse and worse).

**Comment by EmSixTeen** [comment]
This was useful for me, but I'd just like to add my modified version. Makes it a table, with columns for created date, modified date, file size, plus ingoing and outgoing links.

```
~~~dataviewjs
function listFileNameIssues(dv) {  
    let pages = dv.pages();  
    let groups = pages.groupBy(p => p.file.name.toLowerCase())  
    let tableRows = [];

    function formatBytes(bytes, decimals = 2) {
        if (bytes === 0) return '0 Bytes';
        const k = 1024;
        const dm = decimals < 0 ? 0 : decimals;
        const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
        const i = Math.floor(Math.log(bytes) / Math.log(k));
        return parseFloat((bytes / Math.pow(k, i)).toFixed(dm)) + ' ' + sizes[i];
    }

    for (let group of groups) {  
        let count = 0  
        for (let page of group.rows.sort(p => p.file.path, 'asc')) {  
            count += 1  
        }  
  
        if (count === 1 ) {  
            continue  
        }  
  
        // Only process groups with duplicates
        for (let page of group.rows.sort(p => p.file.path, 'asc')) {  
            tableRows.push([
                page.file.link, 
                page.file.path, 
                page.file.cday.toISODate(), 
                page.file.mday.toISODate(),
                formatBytes(page.file.size),
                page.file.inlinks.length, 
                page.file.outlinks.length
            ]);
        }  
    }
    
    if (tableRows.length > 0) {
        dv.table(
            ["File Name", "Full Path", "Created Date", "Modified Date", "Size", "In-Links", "Out-Links"], 
            tableRows
        );
    } else {
        dv.paragraph("No duplicate file names found.");
    }
}

listFileNameIssues(dv);
~~~
```

I only have 'Enable JavaScript queries' enabled, don't need inline, and the dataview JS keyword is `dataviewjs`.
